### ISSUE TITLE
Image Pull Back-off

### ISSUE THREAD

**Issue by durandom** [AICoE/openshift_kubeflow_workshop#1]
I'm getting `Error: ImagePullBackOff` in the RH demo env.
See [here](https://master.brnocz-f8a3.openshiftworkshop.com/console/project/kubeflow/browse/pods/training-distributed-chief-0?tab=events)

That image is there though: https://master.brnocz-f8a3.openshiftworkshop.com/console/project/kubeflow/browse/images/training

In the xci09.lab deployment it's working. Same config for the ImageStream and buildconfig and the same container specs for the pod.

**Comment by pdmack** [comment]
I suspect it works on xci09 because you are a cluster-admin. Related to #2.

**Comment by durandom** [comment]
Oh. on RHDPS I'm cluster admin too

**Comment by pdmack** [comment]
Sorry, thought it was due to you trying to launch as user1 from user1 NS.

**Comment by pdmack** [comment]
So regardless of cluster-admin v. userX, this works in RHPDS:
```
oc apply -f build_config_training.yaml
oc start-build buildconfig.build.openshift.io/training
oc run training --image training
```

**Comment by durandom** [comment]
yes, works for me now too. 
But it wasn't working the other day.... 
Did you change something in the OpenShift cluster setup?

**Comment by goern** [comment]
is this still valid?
